packages:
  - docs
  - tests
  - fixtures/*
  - packages/*
  - private/*

hoistWorkspacePackages: false

ignoredBuiltDependencies:
  - core-js-pure

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - docsify
  - esbuild
  - puppeteer
  - unrs-resolver

preferWorkspacePackages: true

publicHoistPattern:
  - '@babel/*'
