packages:
  - docs
  - tests
  - fixtures/*
  - packages/*
  - private/*

configDependencies:
  pnpm-plugin-sku: 0.0.1+sha512-9tebopr+ruP0nprOotkf8IeMASkXzYdsZuJgOHXhULQLDmg0MkDsPw/zX8P0LcyrImjqQQSXfRvoaWYNXgtrkw==

hoistWorkspacePackages: false

ignoredBuiltDependencies:
  - core-js-pure

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - docsify
  - esbuild
  - puppeteer
  - unrs-resolver

preferWorkspacePackages: true

publicHoistPattern:
  - '@babel/*'

# This is needed so that the React 18 fixture doesn't clobber React 19 in every other fixture. We can remove this once we've dropped React 18 support.
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
dedupeInjectedDeps: false
