packages:
  - docs
  - tests
  - fixtures/*
  - packages/*
  - private/*

catalog:
  '@types/node': ^22.18.8
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@vanilla-extract/vite-plugin': ^5.1.1
  '@vocab/vite': ^0.3.1
  braid-design-system: ^34.0.0
  commander: ^14.0.1
  # 05/08/25: there is currently a bug in later versions of jiti that break eslint ts support. Pinning to 2.4.2 fixes the issue. (last checked with v2.6.1)
  # 12/11/25: Unpinning for now and using JS eslint config because jiti peer deps from other packages are causing issues. We can re-evaluate later.
  jiti: ^2.4.2
  react: ^19.1.0
  react-dom: ^19.1.0
  vite: ^7.2.6
  vitest: ^4.0.15
  debug: ^4.4.3
  '@types/debug': '^4.1.12'

overrides:
  esbuild: ~0.27.0

ignoredBuiltDependencies:
  - core-js-pure

linkWorkspacePackages: deep

onlyBuiltDependencies:
  - '@swc/core'
  - docsify
  - esbuild
  - unrs-resolver
  - sku

preferWorkspacePackages: true

publicHoistPattern:
  - '@babel/*'
