packages:
  - docs
  - tests
  - fixtures/*
  - packages/*
  - private/*

configDependencies:
  pnpm-plugin-sku: 0.0.1+sha512-9tebopr+ruP0nprOotkf8IeMASkXzYdsZuJgOHXhULQLDmg0MkDsPw/zX8P0LcyrImjqQQSXfRvoaWYNXgtrkw==

hoistWorkspacePackages: false

ignoredBuiltDependencies:
  - core-js-pure

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - docsify
  - esbuild
  - puppeteer
  - unrs-resolver

preferWorkspacePackages: true

publicHoistPattern:
  - '@babel/*'
