packages:
  - docs
  - tests
  - fixtures/*
  - packages/*
  - private/*

configDependencies:
  pnpm-plugin-sku: 0.0.1+sha512-9tebopr+ruP0nprOotkf8IeMASkXzYdsZuJgOHXhULQLDmg0MkDsPw/zX8P0LcyrImjqQQSXfRvoaWYNXgtrkw==

hoistWorkspacePackages: false

ignoredBuiltDependencies:
  - core-js-pure

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - docsify
  - esbuild
  - puppeteer
  - unrs-resolver

preferWorkspacePackages: true

publicHoistPattern:
  - '@babel/*'

# This is needed so that the React 18 fixture doesn't clobber React 19 in every other fixture. We can remove this once we've dropped React 18 support.
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

# Catalogue works, but it does raise warnings on install.
# @see https://github.com/pnpm/pnpm/issues/9662
catalog:
  # 05/08/25: there is currently a bug in later versions of jiti that break eslint ts support. Pinning to 2.4.2 fixes the issue.
  jiti: 2.4.2
  vite: ^7.0.6
  '@vanilla-extract/vite-plugin': ^5.1.1
  '@vocab/vite': ^0.2.3
