packages:
  - docs
  - tests
  - fixtures/*
  - packages/*
  - private/*

catalog:
  '@types/node': ^20.19.9
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  '@vanilla-extract/vite-plugin': ^5.1.1
  '@vocab/vite': ^0.2.3
  braid-design-system: ^33.11.0
  jiti: 2.4.2
  react: ^19.1.0
  react-dom: ^19.1.0
  vite: ^7.0.6
  vitest: ^3.2.3

catalogs:
  react18:
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1

configDependencies:
  pnpm-plugin-sku: 0.0.1+sha512-9tebopr+ruP0nprOotkf8IeMASkXzYdsZuJgOHXhULQLDmg0MkDsPw/zX8P0LcyrImjqQQSXfRvoaWYNXgtrkw==

ignoredBuiltDependencies:
  - core-js-pure

injectWorkspacePackages: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - docsify
  - esbuild
  - puppeteer
  - unrs-resolver

preferWorkspacePackages: true

publicHoistPattern:
  - '@babel/*'

syncInjectedDepsAfterScripts:
  - build
