import _traverse from '@babel/traverse';
import _generate from '@babel/generator';
import * as t from '@babel/types';
import type { Plugin } from 'vite';
import {
  VITE_LOADABLE_IMPORT,
  WEBPACK_LOADABLE_IMPORT,
} from './helpers/constants.js';
import { getViteLoadableSpecifierName } from './helpers/getViteLoadableSpecifierName.js';
import { injectModuleID } from './helpers/injectModuleID.js';
import {
  assertSingleLoadableRuntime,
  parseLoadableSource,
  rewriteWebpackLoadableImportsInAst,
} from './helpers/rewriteWebpackLoadableImports.js';
import { getExecuteCommand } from '@sku-private/utils';
import { makePluginName } from '../../helpers/makePluginName.js';
import { convertLoadableDepOptimizePlugin } from '../esbuild/convertLoadableDepOptimizePlugin.js';

// These packages are CJS. Node's interop nests their export under `default`, while a
// bundler's interop unwraps it.
const traverse = _traverse.default ?? _traverse;
const generate = _generate.default ?? _generate;

interface PluginOptions {
  /**
   * Enables extensive build logs
   */
  debug?: boolean;
  /**
   * Convert loadable import from webpack to vite
   */
  convertFromWebpack?: boolean;
}

// Modules to scan for dynamic imports.
const include = /\.[cm]?[jt]sx?$/;

// dev server served modules carry a query string, e.g. `?v=`, which has to be removed.
const cleanId = (id: string) => id.split('?')[0];

// Find all JSX files that have the `loadable` import.
// Find the `loadable` import and inject the moduleId into the third argument.
// ModuleId should be the path of the file relative to the project root.
// This corresponds with the manifest.json that is generated by Vite.
export function preloadPlugin({
  debug,
  convertFromWebpack,
}: PluginOptions = {}): Plugin {
  const lazyImportedModules = new Set();
  const injectedModules = new Set();
  let count = 0;
  return {
    name: makePluginName('preload'),

    ...(convertFromWebpack
      ? {
          config: () => ({
            optimizeDeps: {
              rolldownOptions: {
                plugins: [convertLoadableDepOptimizePlugin()],
              },
            },
          }),
        }
      : {}),

    // This transform applies to bundled code only.
    // Pre-bundled or optimized code is not transformed and is handled in optimizeDeps.rolldownOptions plugin instead.
    transform(code, rawId) {
      const isSsr = this.environment?.name === 'ssr';
      const id = cleanId(rawId);

      if (!include.test(id)) {
        return null;
      }

      const { hasWebpack, hasVite } = assertSingleLoadableRuntime(code, id);

      if (!hasWebpack && !hasVite) {
        return null;
      }

      if (hasWebpack && !convertFromWebpack) {
        console.log(
          `Found '${WEBPACK_LOADABLE_IMPORT}' import in '${id}'. This import is invalid in a Vite application. Please install '@sku-lib/vite' and run '${getExecuteCommand(['@sku-lib/codemod', 'transform-vite-loadable'])}' to update all imports.`,
        );
      }

      const ast = parseLoadableSource(code);

      if (convertFromWebpack && hasWebpack) {
        rewriteWebpackLoadableImportsInAst(ast);
      }

      // Inject the module ID into the third argument of the `loadable()` call.
      let injected = false;
      let loadableFunctionIdentifier = 'loadable';

      traverse(ast, {
        ImportDeclaration(importPath) {
          if (
            t.isStringLiteral(importPath.node.source, {
              value: VITE_LOADABLE_IMPORT,
            })
          ) {
            loadableFunctionIdentifier =
              getViteLoadableSpecifierName(importPath);
          }
        },
        CallExpression(callPath) {
          // only inject the module ID for ssr builds.
          if (
            callPath
              .get('callee')
              .isIdentifier({ name: loadableFunctionIdentifier }) &&
            isSsr
          ) {
            injected = injectModuleID({
              callPath,
              id,
            });
          }
        },
      });

      if (injected) {
        if (debug) {
          this.info('Injected moduleId in React component');
        }
        count++;
        injectedModules.add(id);
      }
      const output = generate(ast, {}, code);
      return {
        code: output.code,
        map: output.map,
      };
    },

    buildEnd() {
      if (debug) {
        for (const lazyModule of lazyImportedModules) {
          if (!injectedModules.has(lazyModule)) {
            this.warn(`${lazyModule} was not injected FOR`);
          }
        }
      }
      this.info(`${count} hook calls injected`);
    },
  };
}
