import _traverse from '@babel/traverse';
import _generate from '@babel/generator';
import * as t from '@babel/types';
import type { Plugin } from 'vite';
import {
  VITE_LOADABLE_IMPORT,
  WEBPACK_LOADABLE_IMPORT,
} from './helpers/constants.js';
import { getViteLoadableSpecifierName } from './helpers/getViteLoadableSpecifierName.js';
import { injectModuleID } from './helpers/injectModuleID.js';
import {
  assertSingleLoadableRuntime,
  createWebpackLoadableImportMessage,
  parseLoadableSource,
  rewriteWebpackLoadableImportsInAst,
} from './helpers/rewriteWebpackLoadableImports.js';
import { makePluginName } from '../../helpers/makePluginName.js';
import { convertLoadableDepOptimizePlugin } from '../esbuild/convertLoadableDepOptimizePlugin.js';

// These packages are CJS. Node's interop nests their export under `default`, while a
// bundler's interop unwraps it.
const traverse = _traverse.default ?? _traverse;
const generate = _generate.default ?? _generate;

interface PluginOptions {
  /**
   * Enables extensive build logs
   */
  debug?: boolean;
  /**
   * Convert loadable import from webpack to vite
   */
  convertFromWebpack?: boolean;
  /**
   * The sku command being run. Remaining webpack loadable imports fail the
   * build on `build` and warn on any other command.
   */
  commandName?: string;
}

// Modules to scan for dynamic imports.
const include = /\.[cm]?[jt]sx?$/;

// dev server served modules carry a query string, e.g. `?v=`, which has to be removed.
const cleanId = (id: string) => id.split('?')[0];

/**
 * If conversion is enabled, rewrites the webpack loadable import to its Vite equivalent.
 * Returns whether a rewrite was attempted.
 */
const convertWebpackLoadable = ({
  hasWebpack,
  ast,
  convertFromWebpack,
}: {
  hasWebpack: boolean;
  ast: t.File;
  convertFromWebpack: boolean | undefined;
}) => {
  if (!hasWebpack || !convertFromWebpack) {
    return false;
  }

  rewriteWebpackLoadableImportsInAst(ast);
  return true;
};

/**
 * Finds the `loadable()` call and injects the moduleId into its third argument.
 * ModuleId should be the path of the file relative to the project root.
 * This corresponds with the manifest.json that is generated by Vite.
 * Callers should only invoke this for ssr builds; the module ID has no purpose on the client.
 */
const injectLoadableModuleId = ({
  ast,
  id,
}: {
  ast: t.File;
  id: string;
}): boolean => {
  let injected = false;
  let loadableFunctionIdentifier = 'loadable';

  traverse(ast, {
    ImportDeclaration(importPath) {
      if (
        t.isStringLiteral(importPath.node.source, {
          value: VITE_LOADABLE_IMPORT,
        })
      ) {
        loadableFunctionIdentifier = getViteLoadableSpecifierName(importPath);
      }
    },
    CallExpression(callPath) {
      if (
        callPath
          .get('callee')
          .isIdentifier({ name: loadableFunctionIdentifier })
      ) {
        injected = injectModuleID({ callPath, id });
      }
    },
  });

  return injected;
};

export function preloadPlugin({
  debug,
  convertFromWebpack,
  commandName,
}: PluginOptions = {}): Plugin {
  const lazyImportedModules = new Set();
  const injectedModules = new Set();
  let count = 0;

  // Vite's own `command` can't be trusted here: the VE compiler's `createServer`
  // reports `serve` during `sku build`, so switch on the sku command instead.
  const isBuild = Boolean(commandName?.startsWith('build'));

  return {
    name: makePluginName('preload'),

    // handle pre-bundled or optimized code that contains webpack loadable imports
    config: () => ({
      optimizeDeps: {
        rolldownOptions: {
          plugins: [convertLoadableDepOptimizePlugin({ convertFromWebpack })],
        },
      },
    }),

    // handles bundled code only.
    transform(code, rawId) {
      const isSsr = this.environment?.name === 'ssr';
      const id = cleanId(rawId);

      if (!include.test(id)) {
        return null;
      }

      const { hasWebpack, hasVite } = assertSingleLoadableRuntime(code, id);
      if (!hasWebpack && !hasVite) {
        return null;
      }

      // The webpack specifier must never survive to the bundle. Conversion is
      // best-effort, so whatever remains after any rewrite is reported.
      const reportRemainingWebpackImport = (outputCode: string) => {
        if (!outputCode.includes(WEBPACK_LOADABLE_IMPORT)) {
          return;
        }

        const message = createWebpackLoadableImportMessage(id);
        if (isBuild) {
          this.error(message);
        } else {
          this.warn(message);
        }
      };

      const ast = parseLoadableSource(code);
      const converted = convertWebpackLoadable({
        ast,
        hasWebpack,
        convertFromWebpack,
      });
      const injected = isSsr && injectLoadableModuleId({ ast, id });

      if (!converted && !injected) {
        reportRemainingWebpackImport(code);
        return null;
      }

      if (injected) {
        if (debug) {
          this.info('Injected moduleId in React component');
        }
        count++;
        injectedModules.add(id);
      }
      const output = generate(ast, {}, code);
      reportRemainingWebpackImport(output.code);
      return {
        code: output.code,
        map: output.map,
      };
    },

    buildEnd() {
      if (debug) {
        for (const lazyModule of lazyImportedModules) {
          if (!injectedModules.has(lazyModule)) {
            this.warn(`${lazyModule} was not injected FOR`);
          }
        }
      }
      this.info(`${count} hook calls injected`);
    },
  };
}
