import styles from './styles.less';

export default () => {
  const el = document.createElement('div');
  el.className = styles.root;
  el.innerHTML = 'This element was generated by the library';
  document.body.appendChild(el);
};
