// @ts-check
const managedConfigBanner = `/** THIS FILE IS GENERATED BY SKU, MANUAL CHANGES WILL BE DISCARDED **/`;

/**
 * Prepends the managed config banner to the provided string.
 * This banner helps users identify files that are managed by sku and should not be manually edited.
 *
 * @param {string} str
 */
const prependWithManagedConfigBanner = (str) =>
  `${managedConfigBanner}\n${str}`;

module.exports = { prependWithManagedConfigBanner };
