name: Deploy docs

on:
  workflow_dispatch:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm build:docs

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site/.vitepress/dist

  deploy-docs:
    name: Deploy docs
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
